create database jandb;
use jandb;
create table student(sid int, sname varchar(50), email varchar(50), fees decimal(10,2));
desc student;
insert into student values (10, 'Ria', 'ria@gmail.com', 15000);
insert into student values (11, 'Roank', 'ronak@gmail.com', 18000);
select * from student;
select sname, fees from student;
select * from student where fees >= 18000;
create table customer(cid int, cname varchar(50), cbal decimal (10,2), city varchar(20));
desc customer;
insert into customer values (123,'Anil',80000,'vadodara');
insert into customer values (234,'Mohan',120000,'rajkot');
select * from customer;
select cname, cbal from customer;
select * from customer where cbal > 100000;
insert into customer values (345,'Snehal',66000,'ahmedabad');
select * from customer;
insert into customer values (456,'hiral',99000.50,'vadodara');
select * from customer;
select * from customer where city = 'vadodara' and cbal > 80000;
select * from customer where city != 'vadodara';
select * from customer where city = 'ahmedabad' or cbal > 100000;
select * from customer where (city = 'ahmedabad' or city = 'rajkot') and cbal > 100000;
select * from customer order by city;
select * from customer order by cname;
select * from customer order by cbal desc;
select * from customer order by cid;
select * from customer order by cbal desc, cname asc;
select * from customer where cname like 'a%';
select * from customer where city like 'a%';
select * from customer where cname like '%i';
select * from customer where city like '%a';
select * from customer where city like 'r%';
select * from customer where cname like '%a%';
select * from customer where cname like '_i%';
select * from customer where cname like '___';
select * from customer where cname like '__i%';
select * from customer where city like '__d%';
insert into student values (15,'Washington','wton@yahoo.com',25000);
select * from student;
select * from customer where city IN ('rajkot', 'vadodara');
select * from customer where city NOT IN ('rajkot', 'vadodara');
select * from customer where cbal between 10000 and 70000;
select cid, cname, cbal as 'Balance' , cbal * 0.05 as 'Discount', (cbal - (cbal * 0.05)) as 'NET Balance' from customer;
select * from student where sname like '%ton';
select * from student where email like '%@g%';
select * from student where email like '%@y%';
select * from student where sname like 'r%';
select * from customer where city in ('rajkot', 'vadodara');
select * from customer where city not in ('vadodara');
select * from student where fees between 15000 and 20000;
select * from student where fees > 20000;
select * from student where fees < 20000;
create table pupil (pid int, pname varchar(50), city varchar(20), dob date);
insert into pupil values (111,'zia','vadodara','2000-01-01');
insert into pupil values (456,'gautam','rajkot','2004-12-15');
insert into pupil values (333,'sahil','vadodara','2005-09-21');
insert into pupil values (999,'kardam','bangluru','2001-06-20');
select * from pupil;
create table salesdata (sale_id int, product_name varchar (30), sale_date date, Quantity_sold int, sales_amount int);
insert into salesdata values (1,'laptop','2025-01-01',3,3000);
insert into salesdata values (2,'phone','2025-01-01',10,5000);
insert into salesdata values (3,'tablet','2025-01-02',5,1500);
insert into salesdata values (4,'headphones','2025-01-03',7,700);
insert into salesdata values (5,'laptop','2025-01-04',2,2000);
insert into salesdata values (6,'tablet','2025-01-04',4,1200);
insert into salesdata values (7,'phone','2025-01-05',8,4000);
insert into salesdata values (8,'headphones','2025-01-06',6,600);
select * from salesdata;
select * from salesdata where sale_date = '2025-01-01';
select product_name, sum(sales_amount) as Total_sales from salesdata where sale_date between '2025-01-01' and '2025-01-31' group by product_name;
select product_name from salesdata where sale_date = '2025-01-03';
select max(sales_amount) from salesdata;
select sum(sales_amount) as total_sales, sum(quantity_sold) as total_quantity from salesdata where sale_date between '2025-01-01' and '2025-01-31';
select * from salesdata where sale_date between '2025-01-01' and '2025-01-03';
select product_name, sum(quantity_sold) as total_quantity from salesdata where sale_date = '2025-01-01' group by product_name having sum(quantity_sold) > 5;




