CREATE DATABASE CUSTOMERDB1;
USE CUSTOMERDB1;
CREATE TABLE CUSTOMER(CID INT, CNAME VARCHAR(40),CITY VARCHAR (20), CONTACTNO VARCHAR(10));
INSERT INTO customer
VALUES (3,'ANUSKA','SURAT','6425789621');
      
SHOW TABLES;
DESCRIBE CUSTOMER;
SELECT * FROM CUSTOMER;
SELECT CNAME,CONTACTNO FROM  CUSTOMER;
SELECT * FROM CUSTOMER WHERE CID = 1;
SELECT * FROM CUSTOMER WHERE CITY = 'VADODARA' OR CITY  = 'SURAT';
SELECT * FROM CUSTOMER WHERE CITY <> 'VADODARA' ;
SELECT * FROM CUSTOMER WHERE CITY = 'SURAT' AND CNAME = 'ANUSKA';
SELECT * FROM CUSTOMER WHERE CID BETWEEN 1 AND 3 ;
SELECT * FROM CUSTOMER WHERE CNAME LIKE 'G%';
SELECT * FROM CUSTOMER WHERE CNAME LIKE '%A';
SELECT * FROM CUSTOMER WHERE CNAME LIKE '_A%';
SELECT * FROM CUSTOMER WHERE CNAME LIKE '___';
SELECT * FROM CUSTOMER WHERE CNAME LIKE '_A__N';

DELETE FROM CUSTOMER; 
DELETE FROM CUSTOMER WHERE CID = 5;
SELECT * FROM CUSTOMER;

UPDATE CUSTOMER SET CITY = 'MUMBAI' WHERE CID = 4;
UPDATE CUSTOMER SET CNAME = 'MOHIT' , CITY = 'NEW DELHI' WHERE CID =4;

