use jandb;
create table officers (officer_id int, officer_name varchar(50), address varchar(50));
insert into officers values (1, 'Ajeet', 'Mau');
select * from officers;
insert into officers values (2, 'Deepika', 'Lucknow');
insert into officers values (3, 'Vimal', 'Faizabad');
insert into officers values (4, 'Rahul', 'Lucknow');
select * from officers;
create table students (student_id int, student_name varchar(50), course_name varchar(50));
insert into students values (1,'Aryan','Java');
insert into students values (2,'Rohini','Hadoop');
insert into students values (3,'Lallu','MongoDB');
select * from students;
select officers.officer_name, officers.address, students.course_name from officers inner join students on officers.officer_id = students.student_id;
select officers.officer_name, officers.address, students.course_name from officers left join students on officers.officer_id = students.student_id;
select officers.officer_name, officers.address, students.student_name, students.course_name from officers right join students on officers.officer_id = students.student_id;
select officers.officer_name, officers.address, students.student_name, students.course_name from students right join officers on students.student_id = officers.officer_id;
select officers.officer_name, officers.address, students.course_name from students inner join officers on officers.officer_id = students.student_id;
select officers.officer_name, officers.address, students.course_name from students left join officers on officers.officer_id = students.student_id;