USE JANN;
SHOW TABLES;
DESCRIBE STUDENT;
INSERT INTO STUDENT VALUES (1, 'RIA', 15000);
INSERT INTO STUDENT VALUES (2, 'ROHAN', 18000);
INSERT INTO STUDENT VALUES (3, 'ZEEL', 25000);
SELECT * FROM STUDENT;
SELECT NAME, FEES FROM student;
